// Frontend-side mock data. Mirrors the shape returned by the FastAPI
// backend so we can iterate on UI without running the backend.

export const mockCategories = [
  { id: "c1", name: "ergonomic lumbar cushion", product_count: 1, avg_margin_pct: 40.65 },
  { id: "c2", name: "portable blender", product_count: 1, avg_margin_pct: 11.77 },
  { id: "c3", name: "pet grooming glove", product_count: 1, avg_margin_pct: 47.58 },
  { id: "c4", name: "silicone food storage bag", product_count: 1, avg_margin_pct: 16.28 },
  { id: "c5", name: "magnetic phone mount", product_count: 1, avg_margin_pct: 28.93 },
  { id: "c6", name: "LED skincare mask", product_count: 1, avg_margin_pct: -1.32 },
  { id: "c7", name: "collapsible water bottle", product_count: 1, avg_margin_pct: 34.96 },
  { id: "c8", name: "desk cable organizer", product_count: 1, avg_margin_pct: 26.48 },
  { id: "c9", name: "insulated lunch bag", product_count: 1, avg_margin_pct: -10.43 },
  { id: "c10", name: "posture corrector brace", product_count: 1, avg_margin_pct: 39.5 },
];

export const mockProducts = [
  { id: "p1", category_id: "c1", cj_product_id: "CJ-10001", title: "Memory Foam Ergonomic Lumbar Cushion", image_url: "https://placehold.co/200x200?text=Lumbar", supply_price: 8.5, sell_price: 29.99, shipping_cost: 4.2, platform_fee: 4.5, net_margin: 12.19, margin_pct: 40.65, supplier_risk_score: 86, sold_count: 1540, stock: 420, supplier_rating: 4.8, recommendation: "PURSUE", explanation: "Healthy 40% margin with a reliable supplier (86 risk score, 1540 fulfilled orders)." },
  { id: "p2", category_id: "c2", cj_product_id: "CJ-10002", title: "USB-Rechargeable Portable Blender 400ml", image_url: "https://placehold.co/200x200?text=Blender", supply_price: 12, sell_price: 24.99, shipping_cost: 5.8, platform_fee: 3.75, net_margin: 2.94, margin_pct: 11.77, supplier_risk_score: 62, sold_count: 620, stock: 180, supplier_rating: 4.6, recommendation: "MONITOR", explanation: "Margin sits at the edge of viable; watch for shipping cost changes before scaling." },
  { id: "p3", category_id: "c3", cj_product_id: "CJ-10003", title: "Silicone Pet Grooming Glove (Pair)", image_url: "https://placehold.co/200x200?text=Pet+Glove", supply_price: 2.1, sell_price: 12.99, shipping_cost: 2.5, platform_fee: 1.95, net_margin: 6.18, margin_pct: 47.58, supplier_risk_score: 91, sold_count: 2400, stock: 800, supplier_rating: 4.9, recommendation: "PURSUE", explanation: "Strong 47% margin, top-tier supplier metrics, and deep stock. Good candidate." },
  { id: "p4", category_id: "c4", cj_product_id: "CJ-10004", title: "Reusable Silicone Food Storage Bag 6-Pack", image_url: "https://placehold.co/200x200?text=Storage", supply_price: 6.8, sell_price: 14.99, shipping_cost: 3.2, platform_fee: 2.25, net_margin: 2.44, margin_pct: 16.28, supplier_risk_score: 55, sold_count: 210, stock: 140, supplier_rating: 4.5, recommendation: "MONITOR", explanation: "Borderline margin and only modest supplier volume; revisit if sold_count grows." },
  { id: "p5", category_id: "c5", cj_product_id: "CJ-10005", title: "Magnetic Car Phone Mount (Dashboard)", image_url: "https://placehold.co/200x200?text=Mount", supply_price: 3.4, sell_price: 9.99, shipping_cost: 2, platform_fee: 1.5, net_margin: 2.89, margin_pct: 28.93, supplier_risk_score: 78, sold_count: 1120, stock: 560, supplier_rating: 4.7, recommendation: "PURSUE", explanation: "Commodity product but 28% margin with strong supplier makes it worth a test order." },
  { id: "p6", category_id: "c6", cj_product_id: "CJ-10006", title: "7-Color LED Photon Skincare Mask", image_url: "https://placehold.co/200x200?text=LED+Mask", supply_price: 22, sell_price: 34.99, shipping_cost: 7.5, platform_fee: 5.25, net_margin: -0.46, margin_pct: -1.32, supplier_risk_score: 48, sold_count: 95, stock: 60, supplier_rating: 4.3, recommendation: "AVOID", explanation: "Shipping + fees wipe out the margin; supplier has only 95 fulfilled orders." },
  { id: "p7", category_id: "c7", cj_product_id: "CJ-10007", title: "Collapsible Silicone Water Bottle 600ml", image_url: "https://placehold.co/200x200?text=Bottle", supply_price: 4.2, sell_price: 14.99, shipping_cost: 3, platform_fee: 2.25, net_margin: 5.24, margin_pct: 34.96, supplier_risk_score: 82, sold_count: 1800, stock: 330, supplier_rating: 4.8, recommendation: "PURSUE", explanation: "35% margin plus a supplier with 1800+ orders and deep stock — good risk profile." },
  { id: "p8", category_id: "c8", cj_product_id: "CJ-10008", title: "Under-Desk Cable Management Tray", image_url: "https://placehold.co/200x200?text=Cables", supply_price: 5.1, sell_price: 16.99, shipping_cost: 4.5, platform_fee: 2.55, net_margin: 4.5, margin_pct: 26.48, supplier_risk_score: 69, sold_count: 430, stock: 110, supplier_rating: 4.6, recommendation: "MONITOR", explanation: "Margin is solid but supplier risk score just under the PURSUE threshold." },
  { id: "p9", category_id: "c9", cj_product_id: "CJ-10009", title: "Insulated Lunch Bag with Shoulder Strap", image_url: "https://placehold.co/200x200?text=Lunch", supply_price: 7.8, sell_price: 11.99, shipping_cost: 3.4, platform_fee: 1.8, net_margin: -1.25, margin_pct: -10.43, supplier_risk_score: 35, sold_count: 80, stock: 40, supplier_rating: 4.2, recommendation: "AVOID", explanation: "Negative margin and a supplier well below our filters — not viable." },
  { id: "p10", category_id: "c10", cj_product_id: "CJ-10010", title: "Adjustable Posture Corrector Brace", image_url: "https://placehold.co/200x200?text=Posture", supply_price: 6.4, sell_price: 22.99, shipping_cost: 3.6, platform_fee: 3.45, net_margin: 9.08, margin_pct: 39.5, supplier_risk_score: 84, sold_count: 1320, stock: 290, supplier_rating: 4.7, recommendation: "PURSUE", explanation: "Classic dropshipping winner: 39% margin, strong supplier, 1300+ fulfilled orders." },
];
